---
- name: Prep VMs for OpenStack
  hosts: all
  user: vagrant
  become: true

  roles:
    - prereqs
    - upgrade
    - networking

- name: Run OpenStack Installation
  hosts: controller-01
  user: vagrant
  become: true

  roles:
    - getplaybooks
    - installansible
    - configuredeployment
    - runplaybooks
