---
- block:
    - name: Run Setup Hosts Playbook
      shell: openstack-ansible setup-hosts.yml > /vagrant/setup-hosts.log
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-hosts.log

  rescue:
    - name: Running openstack-ansible setup-hosts.yml
      shell: openstack-ansible setup-hosts.yml > /vagrant/setup-hosts.log
      args:
        chdir: /opt/openstack-ansible/playbooks

- block:
    - name: Run Infrastructure Playbooks
      shell: openstack-ansible --forks 2  setup-infrastructure.yml > /vagrant/setup-infrastructure.log
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-infrastructure.log

  rescue:
    - name: Running openstack-ansible setup-infrastructure.yml
      shell: openstack-ansible --forks 1 setup-infrastructure.yml > /vagrant/setup-infrastructure.log
      args:
        chdir: /opt/openstack-ansible/playbooks

- name: Configure Galera for HA Proxy
  shell: /vagrant/galera_haproxy.sh

- block:
    - name: Run OpenStack Playbooks
      shell: openstack-ansible --forks 2  setup-openstack.yml > /vagrant/setup-openstack.log
      args:
        chdir: /opt/openstack-ansible/playbooks
        creates: /vagrant/setup-openstack.log

  rescue:
    - name: Running openstack-ansible setup-openstack.yml
      shell: openstack-ansible --forks 1 setup-openstack.yml > /vagrant/setup-openstack.log
      args:
        chdir: /opt/openstack-ansible/playbooks
