---
- name: Ensure Apt directory exists
  file: path=/etc/apt/apt.conf.d state=directory mode=0755

- name: Apt Proxy Config
  template: src=01squid.j2 dest=/etc/apt/apt.conf.d/01squid.conf owner=root group=root mode=0644

- name: Update Apt Cache
  apt:
    update_cache: yes

- name: Upgrade Ubuntu Packages
  apt:
    upgrade: safe
    force: yes
